#!/usr/local/bin/bzt --option=modules.console.disable=true
---

scenarios:
  staging:
    default-address: http://54.210.176.248:8000
    requests:
    - include-scenario: home-page
    - include-scenario: reservation

provisioning: cloud

execution:
  locations:
    us-east-1: 1
  concurrency: 
    cloud: 65
  hold-for: 3m
  ramp-up: 3m
  scenario: staging

services:
- module: passfail
  criteria:
  - avg-rt of Home>150ms for 10s, stop as failed
  - fail of Home>1% for 10s, stop as failed
  - avg-rt of reservation>5s for 10s, stop as failed
  - fail of reservation>10% for 10s, stop as failed

modules:
  blazemeter:
    address: "https://loadtest.dynatrace.com"
    data-address: "https://keynote-dataservice.blazemeter.com/"
  cloud:
    address: "https://loadtest.dynatrace.com"
    test: simple_travel staging
    project: simple_travel


